import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path:'/',
      redirect:'/staff',
      component:()=>import('@/page/index'),
      children:[
        {
          path:'staff',
          component:()=>import('@/page/staff')
        }
      ]
    },
    {
      path:'/asset',
      redirect:'/asset/staff',
      component:()=> import('@/page/index'),     //按需加载组件
      children:[
        {
          path:'staff',
          component:()=>import('@/page/staff')
        },
        {
          path:'car',
          component:()=>import('@/page/asset/car')
        },
        {
          path:'invoice',
          component:()=>import('@/page/asset/invoice')
        },
        {
          path:'card',
          component:()=>import('@/page/asset/card')
        },
        {
          path:'icp',
          component:()=>import('@/page/asset/icp')
        },
        {
          path:'brand',
          component:()=>import('@/page/asset/brand')
        },
        {
          path:'workplace',
          component:()=>import('@/page/asset/workplace')
        },
        {
          path:'storage',
          component:()=>import('@/page/asset/storage')
        },
        {
          path:'receive',
          component:()=>import('@/page/asset/receive')
        },
        {
          path:'borrow',
          component:()=>import('@/page/asset/borrow')
        },
        {
          path:'allot',
          component:()=>import('@/page/asset/allot')
        },
        {
          path:'rent',
          component:()=>import('@/page/asset/rent')
        },
        {
          path:'office',
          component:()=>import('@/page/asset/office')
        },
        {
          path:'changeInfo',
          component:()=>import('@/page/asset/changeInfo')
        },
        {
          path:'tab',
          component:()=>import('@/page/first/tab')
        },
        {
          path:'chart',
          component:()=>import('@/page/first/chart')
        }
      ]
    },
    {
      path:'/system',
      redirect:'',
      component:()=> import('@/page/index'),     //按需加载组件
      children:[
        {
          path:'/system',
          component:()=>import('@/page/system/index')
        },
        {
          path:'organization',
          component:()=>import('@/page/system/organization')
        },
        {
          path:'roles',
          component:()=>import('@/page/system/roles')
        },
        {
          path:'user',
          component:()=>import('@/page/system/user')
        }



      ]
    },
    {
      path:'/login',
      component:()=>import('@/page/login')
    },
    {
      path:'/test',
      component:()=>import('@/page/test')
    }
  ]
})
